[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install",
  "cd ../server && npm install"
]

[phases.build]
cmds = [
  "export VITE_API_URL=https://web-production-bf4ac.up.railway.app && cd client && npm run build",
  "cd ../server && npx prisma generate",
  "cd ../server && npx prisma db push",
  "cd ../server && npm run setup-db"
]

[start]
cmd = "node index.js"

[variables]
NODE_ENV = "production"
VITE_API_URL = "https://web-production-bf4ac.up.railway.app"
