[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install",
  "cd ../server && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd ../server && npx prisma generate"
]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"
